import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "../globals.css";
import { Toaster } from "sonner";
import { CartProvider } from "@/contexts/cart-context";
import NextAuthSessionProvider from "@/contexts/session-provider";
import { SiteHeader } from "@/components/site-header";
import { SiteFooter } from "@/components/site-footer";
import { DiscountBanner } from "@/components/discount-banner";

// const geistSans = Geist({
//     variable: "--font-geist-sans",
//     subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//     variable: "--font-geist-mono",
//     subsets: ["latin"],
// });

export const metadata: Metadata = {
    title: "Lucky Liang E-scooters",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <NextAuthSessionProvider>
            <CartProvider>
                <DiscountBanner />
                <SiteHeader />
                {children}
                <Toaster richColors position="top-right" />
                <SiteFooter />
            </CartProvider>
        </NextAuthSessionProvider>
    );
}
